name: whimsify
description: A preloved marketplace app - give your cute items a new home!
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4  
  provider: ^6.1.1
  supabase_flutter: ^2.6.0
  flutter_dotenv: ^5.1.0
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  geolocator: ^14.0.2
  geocoding: ^5.0.0
  google_maps_flutter: ^2.7.0
  http: ^1.2.1
  uuid: ^4.4.0
  google_mlkit_smart_reply: ^0.13.0   
  app_links: ^6.3.0   
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^22.3.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/branding/whimsify_logo.jpeg
