// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB62-Wn5k5xtcV3OhwRxMEOh1RGDdi-U5I',
    appId: '1:819883756765:web:82788fa8924c70dc769f34',
    messagingSenderId: '819883756765',
    projectId: 'whimsify-app',
    authDomain: 'whimsify-app.firebaseapp.com',
    databaseURL: 'https://whimsify-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'whimsify-app.firebasestorage.app',
    measurementId: 'G-K1QF3QJ4T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5yqfl9tIEuH3j9UGxVdouWWize4X0_N0',
    appId: '1:819883756765:android:06c1f8ed7a8bc7d1769f34',
    messagingSenderId: '819883756765',
    projectId: 'whimsify-app',
    databaseURL: 'https://whimsify-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'whimsify-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNNzZGRQ3xE7TmzVqFCXJN3lp9di0ySSM',
    appId: '1:819883756765:ios:95a04574e4c24895769f34',
    messagingSenderId: '819883756765',
    projectId: 'whimsify-app',
    databaseURL: 'https://whimsify-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'whimsify-app.firebasestorage.app',
    iosBundleId: 'com.example.whimsify',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNNzZGRQ3xE7TmzVqFCXJN3lp9di0ySSM',
    appId: '1:819883756765:ios:95a04574e4c24895769f34',
    messagingSenderId: '819883756765',
    projectId: 'whimsify-app',
    databaseURL: 'https://whimsify-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'whimsify-app.firebasestorage.app',
    iosBundleId: 'com.example.whimsify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB62-Wn5k5xtcV3OhwRxMEOh1RGDdi-U5I',
    appId: '1:819883756765:web:ec7f8eb3d4b6efab769f34',
    messagingSenderId: '819883756765',
    projectId: 'whimsify-app',
    authDomain: 'whimsify-app.firebaseapp.com',
    databaseURL: 'https://whimsify-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'whimsify-app.firebasestorage.app',
    measurementId: 'G-MJWY58YGJX',
  );
}
